name: n_square_international
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  get: ^4.7.3
  dio: ^5.9.1
  video_player: ^2.8.1
  chewie: ^1.7.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  carousel_slider: ^5.1.2

  share_plus: ^12.0.1
  cached_network_image: ^3.4.1
  just_audio: ^0.10.5
  audio_service: ^0.18.12
  audio_session: ^0.1.16
  audio_video_progress_bar: ^2.0.3

  shared_preferences: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.1
  razorpay_flutter: ^1.3.8

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  firebase_messaging: ^15.0.0
  google_sign_in: ^6.2.2

  # Security
  no_screenshot: ^0.0.1

  # Notifications
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo2.png"
  min_sdk_android: 21 # android min sdk value

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/video/
    - assets/logo2.png
